project:
  type: book
  output-dir: _book

book:
  title: "The MorFishJ User Manual"
  subtitle: MorFishJ v{{< var version >}}
  author: "Mattia Ghilardi"
  date: last-modified
  site-url: https://mattiaghilardi.github.io/MorFishJ_manual/
  repo-url: https://github.com/mattiaghilardi/MorFishJ_manual
  repo-branch: main
  repo-actions: [issue]
  
  image: images/logo/MorFishJ_logo.png
  sharing: [twitter, facebook]
  downloads: [pdf]
  twitter-card: 
    creator: "@MattiaGhila"

  page-footer:
    center:
      - text: MorFishJ
        href: https://github.com/mattiaghilardi/MorFishJ
      - text: "License"
        href: http://creativecommons.org/licenses/by-nc-sa/4.0/
    background: light

  sidebar: 
    logo: images/logo/MorFishJ_logo.png
    pinned: true
    alignment: center
    background: light
    style: docked
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - GUI.qmd
    - set_scale.qmd
    - straighten_rotate.qmd
    - main_traits.qmd
    - head_angles.qmd
    - gut_traits.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    mainfont: "Roboto"
    fig-cap-location: bottom
  pdf:
    documentclass: scrreprt
