# Installation

[ImageJ](https://imagej.net/ij/) is an open source image processing program commonly used by researchers to extract morphometric data from fish images. As such, `MorFishJ` has been developed as an extension of this software and it can be used in both ImageJ 1.x and Fiji (ImageJ2) distribution.

Therefore, the installation of ImageJ (instructions [here](https://imagej.net/ij/download.html)) or Fiji (instructions [here](https://imagej.net/software/fiji/downloads)) is required before installing `MorFishJ`.

::: {.callout-warning}
`MorFishJ` depends on `ImageJ {{< var IJ_dep_version >}}`, thus, if ImageJ/Fiji was previously installed, first check the current ImageJ version below the toolbar. If it is older than {{< var IJ_dep_version >}}, to update ImageJ click **Help --\> Update ImageJ...**, choose the latest version and click OK. Then ImageJ/Fiji must be restarted.
:::

Once ImageJ/Fiji is installed/updated, proceed with installing `MorFishJ` following these steps:

1. Download `MorFishJ v{{< var version >}}` from [here](https://github.com/mattiaghilardi/MorFishJ/releases/tag/v{{< var version >}}) as a `ZIP` file.
2. Extract the content.
3. Copy the folder named `MorFishJ` (NOT the entire downloaded folder) in the `ImageJ/plugins/` or `Fiji.app/plugins/` directory.

Now `MorFishJ` is installed. Open ImageJ/FIJI and click **Plugins --\> MorFishJ --\> MorFishJ GUI**. The Graphical User Interface (GUI) ([Chapter -@sec-gui]) of `MorFishJ` appears in the upper left corner of the screen.

::: {.callout-tip}
In Fiji the *Plugins* menu is often crowded, thus it may be easier to use the `Search` field under the toolbar to find and start `MorFishJ`.
:::

::: {.callout-warning}
Starting with version 0.4.0 `MorFishJ` depends on the Java library `jsoup`. While this library is included by default in Fiji, it is not included in ImageJ 1.x. Thus, when trying to start `MorFishJ`, you may encounter the following error: `ImportError: No module named jsoup`. If this happens, download the `jsoup` jar file from [here](https://jsoup.org/download) and place it in the `ImageJ/plugins/jars` directory. Restart ImageJ and the issue should be resolved.
:::