on:
  push:
    branches: master
  pull_request:
    branches: master
  # to be able to trigger a manual build
  workflow_dispatch:
  
name: Build Book

jobs:
  build-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTex to build PDF book
          tinytex: true
      
      - name: Render book to all formats
        # Add any command line argument needed
        run: |
          quarto render
      
      - name: Deploy 🚀
        # only deploy when push to master
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folders and files to be preserved. Older versions of the manual.
          clean-exclude: |
            v0.3.0/**
            v0.2.2/**
            v0.2.1/**
            v0.2.0/**
            v0.1.0/**
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: _book
