on:
  push:
    branches: main
  pull_requests:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:
  
name: Build Book

jobs:
  build-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -uses: actions/checkout@v2
      
      -name: Install Quarto
       uses: quarto-dev/quarto-actions/install-quarto@v1
       with:
        # To install LaTex to build PDF book
        tinytex: true
      
      -name: Render book to all formats
      # Add any command line argument needed
       run: |
        quarto render
      
      -name: Deploy
       # only deploy when push to main
       if: github.event_name != 'pull_request'
       uses: JamesIves/github-pages-deploy-action@v4
       with:
        # The branch the action should deploy to.
        branch: gh-pages
        # The folder the action should deploy.
        folder: _book
      